### ISSUE TITLE
Unexpected error about v6 domain

### ISSUE THREAD

**Issue by Konano** [YtFlow/YtFlowApp#14]
![image](https://user-images.githubusercontent.com/22500116/133056310-8aa5df86-3c8d-4405-a5c1-050b147f4e7e.png)

It happens when I filled server with v6 domain.

**Comment by bdbai** [comment]
[YtFlow (next)](https://github.com/YtFlow/YtFlowApp/releases/tag/v1.2.0) should be able to handle IPv6 hosts properly.
