### ISSUE TITLE
Crush after run

### ISSUE THREAD

**Issue by hooddy** [YtFlow/YtFlowApp#17]
Last update crush after run. Win10x6422h2

**Comment by bdbai** [comment]
Hi @hooddy , may I know which version of YtFlow you are currently using?

You may also try resetting app data from Settings app (see https://answers.microsoft.com/en-us/windows/forum/all/app-cache/8f042073-b722-4a50-a2d9-81216a22b75b), or reinstall the app.

**Comment by hooddy** [comment]
> Hi @hooddy , may I know which version of YtFlow you are currently using?
> 
> You may also try resetting app data from Settings app (see https://answers.microsoft.com/en-us/windows/forum/all/app-cache/8f042073-b722-4a50-a2d9-81216a22b75b), or reinstall the app.

Current one from MS Store (updated by itself). Ill try reset reinstalling this nite.

**Comment by bdbai** [comment]
Do you have Visual Studio installed on your PC? If so, please try to attach the debugger onto the app. See https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-deployed-apps .
Otherwise, a crash dump might be helpful. Refer to https://social.msdn.microsoft.com/Forums/windowsapps/en-US/9287d032-e236-4b81-83da-e58fdecd7603/uwp-get-the-crash-dump-file-for-my-app?forum=wpdevelop and https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps?redirectedfrom=MSDN for collecting crash dumps.

**Comment by hooddy** [comment]
no i don't. unfortunately second trick with registry doesn't have any effect - there is no dumps in those folder.
well the app is just close itself after run. i dunno why. which VS version to use?

**Comment by bdbai** [comment]
Visual Studio 2022 with Universal Windows Platform development workload should work.

**Comment by hooddy** [comment]
well its in russian ui im sorry

![01](https://user-images.githubusercontent.com/6899176/235754371-267b172c-41ff-40ba-aa39-98d6122e192a.png)

**Comment by bdbai** [comment]
@hooddy Could you share a dump file captured by Visual Studio at the point of first crash? See https://learn.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2022#BKMK_Create_a_dump_file

**Comment by hooddy** [comment]
Here it is https://drive.google.com/file/d/1nXvY-CXMKwJ1KKX4hWTXFdnThBq2ZVAY/view?usp=sharing

**Comment by bdbai** [comment]
Thanks for your feedback @hooddy ! May I confirm that there are some non-ASCII characters in your username?

**Comment by hooddy** [comment]
> Thanks for your feedback @hooddy ! May I confirm that there are some non-ASCII characters in your username?

well no it doesn't.  Latin only. But Windows UI is Russian for sure.

**Comment by bdbai** [comment]
@hooddy try [v1.1.1](https://github.com/YtFlow/YtFlowApp/releases/tag/v1.1.1) and see if it works? Also attach a crash dump if still not working. Thanks!

**Comment by hooddy** [comment]
> @hooddy try [v1.1.1](https://github.com/YtFlow/YtFlowApp/releases/tag/v1.1.1) and see if it works? Also attach a crash dump if still not working. Thanks!
nope it is still crashed...
https://drive.google.com/file/d/1Kbk8qBxgiuP42IvI1Eu0Hq62IcYN2dXl/view?usp=sharing

**Comment by bdbai** [comment]
@hooddy It looks like a feature (AVX2) that your CPU does not support is triggered. May I check if you are using a Sandy Bridge processor (iX-2XXX or iX-3XXX)?

**Comment by hooddy** [comment]
> @hooddy It looks like a feature (AVX2) that your CPU does not support is triggered. May I check if you are using a Sandy Bridge processor (iX-2XXX or iX-3XXX)?

CPU Type	QuadCore Intel Core i7-2600, 3433 MHz (35 x 98)
CPU Alias	Sandy Bridge-DT
Instruction Set	x86, x86-64, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, AES

**Comment by bdbai** [comment]
@hooddy try [v1.1.2](https://github.com/YtFlow/YtFlowApp/releases/tag/v1.1.2)?

**Comment by hooddy** [comment]
> @hooddy try [v1.1.2](https://github.com/YtFlow/YtFlowApp/releases/tag/v1.1.2)?

yep its run finally. but there is another question will it works on w10m w10rt? previous stable release 0.1 does.

**Comment by bdbai** [comment]
@hooddy 

> yep its run finally.

Thanks for your feedback! I am going to close this issue. Feel free to start a new one should you have any questions. 

> will it works on w10m w10rt? previous stable release 0.1 does.

By right it should work on Windows 10 Mobile 1703, tested on my Lumia 640. For Windows RT, I don't have a device running that so unfortunately I can't tell.
