### ISSUE TITLE
W10M connect error

### ISSUE THREAD

**Issue by hooddy** [YtFlow/YtFlowApp#18]
Well on my W10M phone (1709 build) i've get this error while trying to connect.
Btw this error on previous release to. And thats strange coz on my W10RT tab its work.
![wp_ss_20230507_0001](https://user-images.githubusercontent.com/6899176/236669246-9085598e-c5db-4521-8ecb-885770d26f5a.png)
![wp_ss_20230507_0002](https://user-images.githubusercontent.com/6899176/236669247-08ede367-7f8a-4a4f-ae84-316c1ba8a744.png)

**Comment by bdbai** [comment]
Try the following steps:

1. Remove the `YtFlow Auto` VPN connection from Settings
2. Reboot device
3. Create `YtFlow Auto` VPN connection from Settings
4. Open YtFlow app, click `Connect`

and see if it persists?

**Comment by hooddy** [comment]
yep it still the same. it is possibly i did rong connection setting within app. can ya advice how to correct add ss connection?

**Comment by bdbai** [comment]
For 691 errors, remove the app from background and reconnect a few times and it should work.

Shadowsocks links are imported from Asset page under any proxy group. Choose `Dynamic Outbound` when you create the profile.

**Comment by hooddy** [comment]
> remove the app from background

i don't get where is it?

**Comment by hooddy** [comment]
No I can't get how it works.

**Comment by bdbai** [comment]
@hooddy I mean the app switcher that you see when you long-press the Back key.

**Comment by hooddy** [comment]
> @hooddy I mean the app switcher that you see when you long-press the Back key.
i got it but i can't get how to set it up on W10M. can ya record some video and put on youtube?

**Comment by bdbai** [comment]
@hooddy you may join the `@YtFlow` Telegram group and find some videos there.

**Comment by hooddy** [comment]
Well it can't recognize ss link

**Comment by hooddy** [comment]
It can't recognize ss link from [VPNsafe](https://t.me/vpnsafebot)

**Comment by bdbai** [comment]
> It can't recognize ss link from [VPNsafe](https://t.me/vpnsafebot)

I noticed there was a `outline=1` parameter in the link obtained from the bot. Currently any extra parameter renders the link unrecognized, which is expected to ensure compatibility.
I am not clear about the compatibility with Outline servers, but it seems to work when I use the server imported by removing the `?outline=1` part at the end.

**Comment by hooddy** [comment]
Anyway I still can't set it up on mobile.

**Comment by bdbai** [comment]
@hooddy You may also set it up on your PC, and then copy the database to your phone. The database is located at LocalAppData/db/main.db.

**Comment by hooddy** [comment]
> @hooddy You may also set it up on your PC, and then copy the database to your phone. The database is located at LocalAppData/db/main.db.

well i see it at
C:\Users\username\AppData\Local\Packages\56263bdbai.YtFlow_5wvpqmt3a9dj6\LocalState\db

so where at my windows 10 phone should i place it?

**Comment by bdbai** [comment]
@hooddy You should be able to find it in the File Manager from Device Portal.
https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-mobile

**Comment by hooddy** [comment]
> @hooddy You should be able to find it in the File Manager from Device Portal. https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-mobile

ok i see LocalAppData folder. but there is no YtFlow in it. It installed for sure
![Снимок экрана (27)](https://github.com/YtFlow/YtFlowApp/assets/6899176/9331bec1-64d6-4e03-8362-3538626deef0)

**Comment by bdbai** [comment]
@hooddy you might have installed the app to the external storage (SD card, `D:`)? Try `C:` instead.
Also make sure to launch the app once to bootstrap the database folder.

**Comment by hooddy** [comment]
> @hooddy you might have installed the app to the external storage (SD card, `D:`)? Try `C:` instead. Also make sure to launch the app once to bootstrap the database folder.

Nope. Its in internal storage

**Comment by bdbai** [comment]
> Anyway I still can't set it up on mobile.

What do you mean by "can’t set it up”?

**Comment by hooddy** [comment]
> > Anyway I still can't set it up on mobile.
> 
> What do you mean by "can’t set it up”?

coz its not workin in anyway with 691 error.

**Comment by bdbai** [comment]
@hooddy This kind of errors are not related to in-app set up. If it really does not work somehow then I suggest resetting your phone and try again.

**Comment by hooddy** [comment]
> @hooddy This kind of errors are not related to in-app set up. If it really does not work somehow then I suggest resetting your phone and try again.

im just wanna to be sure that ya personally check it on your own mobile and its works for ya.

**Comment by bdbai** [comment]
> > @hooddy This kind of errors are not related to in-app set up. If it really does not work somehow then I suggest resetting your phone and try again.
> 
> im just wanna to be sure that ya personally check it on your own mobile and its works for ya.

![wp_ss_20230525_0003](https://github.com/YtFlow/YtFlowApp/assets/5270106/b6e2f498-2ee7-40b0-9d32-58fcdf60f0d1)

Yup it works without issues.
