### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by bwjohns4** [YtFlow/YtFlowApp#19]
How do you debug what's running on the VpnPlugin implementation code that's running from the background task? I'm doing something similar and CANNOT get the background task to launch (or at least I can't tell that it's launching). Is there a way to put debug statements in it? If you're interested, I would love to hire you for your assistance in getting my implementation working. I'm at quite a deadend with this.

**Comment by bdbai** [comment]
> How do you debug what's running on the VpnPlugin implementation code that's running from the background task?

You can actually put a breakpoint in your background task startup and start a debug session of your app in Visual Studio.

**Comment by bdbai** [comment]
Also see https://github.com/ysc3839/UWPToyVpn/issues/5#issuecomment-1953508398
