### ISSUE TITLE
Release 0.4.0.0 not work

### ISSUE THREAD

**Issue by CodeForCSharp** [YtFlow/YtFlowApp#2]
OS version:Windows 10 Pro 19041.84
Platform:PC SurfaceBook
Step:
1.Create an config(***** only the mask,not the fact port)
![image](https://user-images.githubusercontent.com/12980468/74601956-af2ac900-50de-11ea-8211-a2ad3de19bb3.png)
![image](https://user-images.githubusercontent.com/12980468/74601969-d4b7d280-50de-11ea-91a2-cfd5c8ac2d52.png)
2. Click connect button
![image](https://user-images.githubusercontent.com/12980468/74601979-00d35380-50df-11ea-88ac-f07d62bc3f8d.png)
Hope:
Work well.
Fact:
CPU run to 100% and the App crash.
Can't connect successful(google can't open)

**Comment by bdbai** [comment]
Domain name as Server Host is not correctly handled yet. Consider use IP address instead.

**Comment by CodeForCSharp** [comment]
OK.It's work!
Hope to support domain name，because the gov sometimes will ban ip frequently.
But Windows have any indicator to remind user under VPN？I can't see it.

**Comment by bdbai** [comment]
@CodeForCSharp Domain name server will be supported only after a DNS client is implemented. 

Unfortunately on Windows Desktop there is no such indicator. Even when the YtFlow VPN connection is on, the VPN switch in Notification Center does not look any different. 
However, on Mobile devices there is an indicator on the Wi-Fi icon.

**Comment by CodeForCSharp** [comment]
After looking for a minute, I found the status can be seen here.
![image](https://user-images.githubusercontent.com/12980468/74602457-91ac2e00-50e3-11ea-8ef0-313cf2c1a0e3.png)
All done.Please close the issue.
