### ISSUE TITLE
ObjectDisposedException occured

### ISSUE THREAD

**Issue by CodeForCSharp** [YtFlow/YtFlowApp#3]
**Platform:** Desktop
**OS Version:** 19041.84
**App Version:** 0.5.0.0
**Problem:**
When using ,this app show a dialog as below
![image](https://user-images.githubusercontent.com/12980468/75094755-18bc4300-55c9-11ea-928c-f1778fe2b5b8.png)
No more log.If you want more log,please tell me how to get it.
**Hope:**
No exception.

**Comment by bdbai** [comment]
Thanks for reporting this issue. We will get it fixed in future releases.

**Comment by bdbai** [comment]
Not reproducible in the next version.
