### ISSUE TITLE
NullReferenceException occured

### ISSUE THREAD

**Issue by CodeForCSharp** [YtFlow/YtFlowApp#4]
**Platform:** Desktop
**OS Version:** 19041.84
**App Version:** 0.5.0.0
**Problem:**
When using ,this app show a dialog as below
![image](https://user-images.githubusercontent.com/12980468/75115736-753c6280-569c-11ea-950a-6f51354cc64e.png)
**Hope:**
No exception.

**Comment by bdbai** [comment]
Noted.
