### ISSUE TITLE
Question:Why some apps not work under open VPN

### ISSUE THREAD

**Issue by CodeForCSharp** [YtFlow/YtFlowApp#5]
1. Unigram can't work with "Without Proxy" Mode.But it can work well on the local socks5 proxy(172.17.255.240:1080).Why?
2. MS Store show "can't not access network" when open.Why?

**Comment by bdbai** [comment]
1. This is because the VPN interface does not include the whole IP range when created. It is an intended behavior such that the connections to the remote server will never be routed to the interface itself, causing an endless recursion.
2. Hopefully will be solved in the future releases.

**Comment by CodeForCSharp** [comment]
OK.Hope to have some workaround with this problem.
